version: "3.5"

services:
  database:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
    env_file:
      - config.env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
